apiVersion: apps/v1
kind: Deployment
metadata:
  name: saarey-deployment
  labels:
    app: saarey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saarey
  template:
    metadata:
      labels:
        app: saarey
    spec:
      containers:
      - name: saarey
        image: haroonarcana/saarey-web-17-5-23:v6
        ports:
        - containerPort: 80
